---
- name: Service redis is active and enabled on system startup
  ansible.builtin.systemd_service:
    name: redis-server
    state: started
    enabled: true
- name: allow redis port
  community.general.ufw:
    port: "{{ redis_port | string }}"
    proto: tcp
    rule: allow
    from_ip: "{{ redis_allow_connect_other_host | default('any') }}"
  when: redis_allow_connect_other_host is defined
